// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGnrQ5FB9tq3EHKnr0F83t2XHyPbDfvAw',
    appId: '1:11560753109:web:73af763b1e1b6924becf5c',
    messagingSenderId: '11560753109',
    projectId: 'helpt-gachon',
    authDomain: 'helpt-gachon.firebaseapp.com',
    storageBucket: 'helpt-gachon.firebasestorage.app',
    measurementId: 'G-0TFFBKRLMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXSTzkqKkX-OuWLsIPgy5IW2jlBUZ3qc',
    appId: '1:11560753109:android:37821860fb8efd72becf5c',
    messagingSenderId: '11560753109',
    projectId: 'helpt-gachon',
    storageBucket: 'helpt-gachon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFDg8TN3UDEIJMRUAphWGY0Yd-qSECY-Y',
    appId: '1:11560753109:ios:4205e9e4a0e64fddbecf5c',
    messagingSenderId: '11560753109',
    projectId: 'helpt-gachon',
    storageBucket: 'helpt-gachon.firebasestorage.app',
    iosBundleId: 'com.helpt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFDg8TN3UDEIJMRUAphWGY0Yd-qSECY-Y',
    appId: '1:11560753109:ios:28eae335295bde2cbecf5c',
    messagingSenderId: '11560753109',
    projectId: 'helpt-gachon',
    storageBucket: 'helpt-gachon.firebasestorage.app',
    iosBundleId: 'com.example.helpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGnrQ5FB9tq3EHKnr0F83t2XHyPbDfvAw',
    appId: '1:11560753109:web:c03fda60b5e3e5f7becf5c',
    messagingSenderId: '11560753109',
    projectId: 'helpt-gachon',
    authDomain: 'helpt-gachon.firebaseapp.com',
    storageBucket: 'helpt-gachon.firebasestorage.app',
    measurementId: 'G-FR9BNBX320',
  );
}
